-- Crear una secuencia
CREATE SEQUENCE secuencia_documentoCinco
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE;

CREATE TABLE documentoCinco (
  id_documento NUMBER DEFAULT secuencia_documentoCinco.NEXTVAL PRIMARY KEY,
  nombre_documento nvarchar2(50)
);


CREATE SEQUENCE secuencia_areaCinco
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE;
  
  
CREATE TABLE areaCinco (
  id_area NUMBER DEFAULT secuencia_areaCinco.NEXTVAL PRIMARY KEY,
  nombre_area nvarchar2(50) not null 
);


CREATE SEQUENCE secuencia_cargoCinco
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE;
  
CREATE TABLE cargoCinco (
  id_cargo NUMBER DEFAULT secuencia_cargoCinco.NEXTVAL PRIMARY KEY,
  nombre_cargo nvarchar2(50) not null 
);



CREATE SEQUENCE secuencia_empleadoCinco
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE;
  
CREATE TABLE empleadoCinco (
  id_empleado NUMBER DEFAULT secuencia_empleadoCinco.NEXTVAL PRIMARY KEY,
  id_documento NUMBER not null,
  id_area NUMBER not null,
  id_cargo NUMBER not null,
  nombre_empleado nvarchar2(50) not null,
  apellido_empleado nvarchar2(50) not null,
  FOREIGN KEY (id_documento) REFERENCES documentoCinco (id_documento),
  FOREIGN KEY (id_area) REFERENCES areaCinco (id_area),
  FOREIGN KEY (id_cargo) REFERENCES cargoCinco (id_cargo)
);



























CREATE TABLE empleado (
  id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  id_documento NUMBER not null,
  id_area NUMBER not null,
  id_cargo NUMBER not null,
  nombre_empleado nvarchar2(50) not null,
  apellido_empleado nvarchar2(50) not null,
  CONSTRAINT pk_empleado PRIMARY KEY (id_empleado),
  FOREIGN KEY (id_documento) REFERENCES documento (id_documento),
  FOREIGN KEY (id_area) REFERENCES area (id_area),
  FOREIGN KEY (id_cargo) REFERENCES cargo (id_cargo)
);


CREATE TABLE documento (
  id_documento NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  nombre_documento nvarchar2(50) not null,
  CONSTRAINT pk_documento PRIMARY KEY (id_documento)
);

CREATE TABLE area (
  id_area NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  nombre_area nvarchar2(50) not null,
  CONSTRAINT pk_area PRIMARY KEY (id_area)
);

CREATE TABLE cargo (
  id_cargo NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  nombre_cargo nvarchar2(50) not null,
  CONSTRAINT pk_cargo PRIMARY KEY (id_cargo)
);

















